# Generated by Django 4.2.23 on 2025-07-26 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medconnect_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_area', models.CharField(choices=[('clinical_research', 'Clinical Research'), ('biomedical_research', 'Biomedical Research'), ('pharmaceutical_research', 'Pharmaceutical Research'), ('genetics_research', 'Genetics Research'), ('epidemiology', 'Epidemiology'), ('public_health', 'Public Health Research'), ('medical_devices', 'Medical Devices Research'), ('other', 'Other Research Areas')], max_length=50)),
                ('institution', models.CharField(help_text='University, Hospital, or Research Institute', max_length=200)),
                ('qualification', models.CharField(help_text='PhD, MD, MSc, etc.', max_length=100)),
                ('research_experience_years', models.PositiveIntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Researcher',
                'verbose_name_plural': 'Researchers',
            },
        ),
        migrations.CreateModel(
            name='ResearchStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_title', models.CharField(max_length=200)),
                ('study_description', models.TextField()),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting Participants'), ('in_progress', 'Study in Progress'), ('completed', 'Study Completed'), ('cancelled', 'Study Cancelled')], default='recruiting', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('compensation', models.CharField(blank=True, help_text='Compensation for participation', max_length=100)),
                ('requirements', models.TextField(blank=True, help_text='Eligibility requirements')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medconnect_app.patient')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medconnect_app.researcher')),
            ],
            options={
                'verbose_name': 'Research Study',
                'verbose_name_plural': 'Research Studies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
