# Generated by Django 4.2.23 on 2025-07-28 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_app', '0004_patientprofile_profile_researcherprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_specialization', models.CharField(blank=True, max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medconnect_app.profile')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
