# Generated by Django 4.2.23 on 2025-07-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_app', '0006_community_communitypost_postcomment_postattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phase', models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III'), ('Phase IV', 'Phase IV'), ('Pre-clinical', 'Pre-clinical')], default='Phase I', max_length=20)),
                ('sponsor', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('eligibility_criteria', models.TextField()),
                ('primary_endpoint', models.TextField()),
                ('estimated_enrollment', models.PositiveIntegerField()),
                ('current_enrollment', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('estimated_completion_date', models.DateField()),
                ('status', models.CharField(choices=[('recruiting', 'Recruiting Participants'), ('in_progress', 'Study in Progress'), ('completed', 'Study Completed'), ('cancelled', 'Study Cancelled')], default='recruiting', max_length=20)),
                ('compensation', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_studies', to='medconnect_app.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('screening', 'Screening'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('rejected', 'Rejected')], default='interested', max_length=20)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('enrolled_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_participations', to='medconnect_app.profile')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='medconnect_app.researchstudy')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('study', 'patient')},
            },
        ),
    ]
