# Generated by Django 5.2.4 on 2025-09-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medconnect_app', '0009_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='medconnect_app.researchstudy'),
        ),
        migrations.CreateModel(
            name='StudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_documents/')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('consent', 'Consent Form'), ('protocol', 'Study Protocol'), ('guideline', 'Guideline'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medconnect_app.researchstudy')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_study_documents', to='medconnect_app.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
